### ISSUE TITLE
Not able to set up caucus-server properly

### ISSUE THREAD

**Issue by prayutsu** [Rishabh-malhotraa/caucus-server#7]
I tried to set up the caucus frontend and backend on my local machine but the app isn't functional in the development server (probably because backend isn't set up properly).
In the installation guide, it is mentioned to add environment variables in a .env file but I need a little help to set up these environment variables. e.g -
```
GITHUB_KEY_CLIENTID = get your key from  https://github.com/settings/applications
```

When I open the mentioned URL, I see a list of apps that have been authenticated with my Github account and I can't find the CLIENT_ID key. 
Also, do I need to change other environment variables in order to make the app functional on my local server?

**Comment by Rishabh-malhotraa** [comment]
Sorry for that; the config is a mess; I never go around to fixing it for a better dev-experience 

I think there has been a change from where you can get the OAuth token
https://github.com/settings/developers

<img width="1436" alt="image" src="https://user-images.githubusercontent.com/54576074/156043744-f6770c0d-901c-43fb-ab5d-fa3c987b24e0.png">

you can get the credentials from `new OAuth app` button on the top right


I think to configure the backend properly, you would need the PostgreSQL dump file to import all the leetcode questions

**Comment by prayutsu** [comment]
Actually "Login as guest" button is working fine,  but none of the other buttons is working on the public room page. Also, I can't fetch the questions in the left panel.
<img width="1440" alt="Screenshot 2022-03-01 at 10 10 09 AM" src="https://user-images.githubusercontent.com/54636525/156106638-3349da38-ba43-48f6-9113-60da7364fad9.png">
<img width="1435" alt="Screenshot 2022-03-01 at 10 11 09 AM" src="https://user-images.githubusercontent.com/54636525/156106652-6e4b196d-861b-4d3b-95f8-b869366eadca.png">

@Rishabh-malhotraa Can you guide me on how to get the Postgresql dump file?

P.S - I have changed the PORT from 5000 to 4000 in several places as I think PORT 5000 is already in use.
Files changed - 
1. .env file of caucus-server 
2. .env file of caucus (frontend)
3. config.keys.ts file of caucus-server

**Comment by Rishabh-malhotraa** [comment]
is the server running properly, can you send me the screenshot of the terminal
Also you need to run this command to start the yjs-socket server
`npx y-websocket-server`

**Comment by prayutsu** [comment]
Here are the screenshots of the console - 
<img width="1107" alt="Screenshot 2022-03-01 at 10 33 10 AM" src="https://user-images.githubusercontent.com/54636525/156108230-b1d7a9f2-ea31-4b6b-92a5-9d87918fdb74.png">
<img width="1105" alt="Screenshot 2022-03-01 at 10 33 18 AM" src="https://user-images.githubusercontent.com/54636525/156108243-c36e1ce0-cf29-4a7f-875d-917e9fc473d2.png">
<img width="1119" alt="Screenshot 2022-03-01 at 10 33 24 AM" src="https://user-images.githubusercontent.com/54636525/156108245-de3e2436-b7b7-4a76-9452-465b7318a5a4.png">

**Comment by prayutsu** [comment]
@Rishabh-malhotraa  Here are the screenshots of the console - <img alt="Screenshot 2022-03-01 at 10 33 10 AM" width="1107" src="https://user-images.githubusercontent.com/54636525/156108230-b1d7a9f2-ea31-4b6b-92a5-9d87918fdb74.png"> <img alt="Screenshot 2022-03-01 at 10 33 18 AM" width="1105" src="https://user-images.githubusercontent.com/54636525/156108243-c36e1ce0-cf29-4a7f-875d-917e9fc473d2.png"> <img alt="Screenshot 2022-03-01 at 10 33 24 AM" width="1119" src="https://user-images.githubusercontent.com/54636525/156108245-de3e2436-b7b7-4a76-9452-465b7318a5a4.png">

**Comment by Rishabh-malhotraa** [comment]
Can you check if real-time collaboration is working by opening two browsers?

Also, you can check if messenger and working and try loading up a question from codeforces

https://codeforces.com/contest/1642/problem/A

**Comment by Rishabh-malhotraa** [comment]
I'll make this repository archive-read only and add the contents to caucus repository to make the setup easier like I did in [Vita](https://github.com/Rishabh-malhotraa/Vita) project

**Comment by prayutsu** [comment]
@Rishabh-malhotraa Real-time collaboration is working but the 
<img width="1440" alt="Screenshot 2022-03-01 at 10 41 09 AM" src="https://user-images.githubusercontent.com/54636525/156108947-2301c8bf-e473-4c9f-9e93-518fc6cedccc.png">
<img width="1439" alt="Screenshot 2022-03-01 at 10 41 13 AM" src="https://user-images.githubusercontent.com/54636525/156108955-5724a659-69bc-4c01-9e75-08c8ac749448.png">
messenger isn't.

**Comment by prayutsu** [comment]
Also I am not able to fetch codeforces or atcoder question

**Comment by prayutsu** [comment]
> I'll make this repository archive-read only and add the contents to caucus repository to make the setup easier like I did in [Vita](https://github.com/Rishabh-malhotraa/Vita) project

That would be great 👍🏽

**Comment by Rishabh-malhotraa** [comment]
I updated the installation process for caucus. You can go to the main repo and follow the [installation steps there](https://github.com/Rishabh-malhotraa/caucus#installation)

I also included the dump files to restore the database locally.

I will be archiving the repository, as I have merged this repository into the caucus.
